language: node_js
node_js:
  - "10.14"
deploy:
  provider: azure_web_apps

before_install:
    - stty cols 80

dist: trusty
sudo: required

addons:
  firefox: "66.0.3"
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &
